### ISSUE TITLE
Screenshot of page?

### ISSUE THREAD

**Issue by Telavian** [RusKnyaz/Optimus#14]
Is it possible to take a screenshot (image) of a page being rendered?
If it is possible, then how is it done?
If it is not possible then will it ever be supported?

**Comment by RusKnyaz** [comment]
This library does not contains any rendering logic. This is intentionally done like this. But there is another package on nuget - [Knyaz.Optimus.Graphics](https://www.nuget.org/packages/Knyaz.Optimus.Graphics). Try it, but keep in mind. It may not work as expected, or may not work at all.

**Comment by Telavian** [comment]
Thanks.
