### ISSUE TITLE
vb.net dom elements

### ISSUE THREAD

**Issue by bettesn** [RusKnyaz/Optimus#15]
Not sure if this is the correct place to ask questions but I can't find any other support forums.

In vb.net the engine retrieves a page ok - I can display it - a google rearch result as it happens.  However

Dim LClasses As ITokenList = _engine.Document.ClassList returns a  0 length list (even though I can see classes in the page source) and
Dim LNodes As List(Of Node) = _engine.Document.ChildNodes returns only 2 nodes:  html and head - even though there are of course dozens of other nodes.

Is vb.net supported?  Am I doing something stupid?

Thanks

**Comment by RusKnyaz** [comment]
1) Document.ClassList should be empty. In real browsers this property is undefined.
2) ChildNodes returns children, not descendants. Most often there are only two such nodes: DocType and html.
3) I can not guarantee that vb.net will work. But I see no reason why this should not be.

**Comment by bettesn** [comment]
Ok I now understand that I need a recursive function to find all the elements or search for a particular one.  Thanks.

**Comment by RusKnyaz** [comment]
You can use one of the approaches suggested here:
https://stackoverflow.com/questions/26325278/how-can-i-get-all-descendant-elements-for-parent-container
