### ISSUE TITLE
Downloading Using Authentication Current Version

### ISSUE THREAD

**Issue by mstoffel-infraserv** [RusKnyaz/Optimus#16]
The version 2.2.5 does not have engine.ResourceProvider.CreateRequest function. How can I utilize my authentication cookies to download files in this version. Access to the cookie container is also not available. If there is another way to make these download file requests please let me know.

Thanks.

**Comment by RusKnyaz** [comment]
Have you tried the approach suggested in the "Download the file by url using ResourceProvider" section of the [document](https://github.com/RusKnyaz/Optimus/blob/develop/docs/snippets.md) ?

Alternatively, you can get cookies through a 'document.cookies' property and create own CookieContainer.

Please let me know if this doesn't work out and describe your scenario in more detail.

**Comment by mstoffel-infraserv** [comment]
What I'm referring to is the approach in the "Download the file by url using ResourceProvider" section does not work with the current version of the DLL as it is missing the CreateRequest function, nor does it have the CookieContainer property. I can build my own CookieContainer from the document.cookies, but I figure I'd try to use built in functionality of the library.

**Comment by RusKnyaz** [comment]
Somehow breaking changes leaked into the minor build. 
Now, I changed Engine's CookieContainer property access from internal to public. You can check it using the dev build [nuget feed](https://ci.appveyor.com/nuget/optimus-private)
