### ISSUE TITLE
The site http://www.kzs.si/ is not loaded correctly

### ISSUE THREAD

**Issue by RusKnyaz** [RusKnyaz/Optimus#2]
open the url: http://www.kzs.si/incl?id=967&team_id=4596801&league_id=undefined&season_id=108919

Expected:
The element with id '33-200-tab-3' is in the DOM.
Observed: 
*There are no element with such an id.
*There are errors in scripts.

**Comment by RusKnyaz** [comment]
Created issue #1

**Comment by RusKnyaz** [comment]
Created issue #2 for the 'TypeError' exception.

**Comment by RusKnyaz** [comment]
Created issue #4 to be able define 'escape' function before page load.

**Comment by MihaMarkic** [comment]
@RusKnyaz With mentioned issues fixed it really seems loading the thing correctly. Will test it a bit further but it looks amazingly good.
