### ISSUE TITLE
Browser configuration

### ISSUE THREAD

**Issue by bettesn** [RusKnyaz/Optimus#21]
I'm trying to set things like user agent, encoding, accept=text and so on for the engine.

Should I  use IResourceProvider?  I cannot find any documentation on how to do this.

**Comment by RusKnyaz** [comment]
I added the sample to the documentation:
```c#
var engine = EngineBuilder.New().ConfigureResourceProvider(x => x.Notify(
    request => { /*modify request here */},
    response => { /*handle response */}
)).Build();
```
Request handler function passed to the Notify method called before the request is sent. The request object is mutable, so you can modify it adding headers.

Another way is to implement own ResourceProvider that inherits IResourceProvider and pass it to EngineBuilder:

```c#
var engine = EngineBuilder.New().SetResourceProvider(yourResourceProvider).Build();
```

**Comment by bettesn** [comment]
Thanks.  I'm using vb.net so I'm having to translate this stuff.  Enginebuilder does not seem to exist in the nuget package (v2.2.6).  I am trying to use the resourceprovider approach:

Dim iRP As IResourceProvider = New ResourceProviderBuilder().Http().Notify('what goes here for request and response?)

Thanks again.

**Comment by RusKnyaz** [comment]
```VB
Dim iRP As IResourceProvider = New ResourceProviderBuilder().Http().Notify(
            Sub(request As Request)
                rem; do something with request
            End Sub,
            Sub(response As ReceivedEventArguments)
                rem; do something with response
            End Sub)
`
