### ISSUE TITLE
Unity and Android support

### ISSUE THREAD

**Issue by TheBricktop** [RusKnyaz/Optimus#23]
Hello, great project here, 
Im currently in progress of evaluating multiple cef adaptations for unity and stumbled upon Yours.
Will it provida support for cross platform development including android?

Is Unity support considered?

**Comment by RusKnyaz** [comment]
I think you should ask Unity developers if they support netstandard/net462 assemblies.

**Comment by TheBricktop** [comment]
Well unity 2019.2 comes with 4.x support so it might be.
