### ISSUE TITLE
Not found EngineBuilder

### ISSUE THREAD

**Issue by dmaco** [RusKnyaz/Optimus#24]
the code below dosent find the EngineBuilder
i have installed the nugged package and 
in a windows form place on top 
using Knyaz.Optimus;
using Knyaz.Optimus.Dom.Elements;

var engine = EngineBuilder.New()
   		    .UseJint()// Enable JavaScripts execution.
   		    .Build(); // Builds the Optimus engine.

**Comment by RusKnyaz** [comment]
The EngineBuilder was added in version 2.3, which has not yet been published. You can compile the library from source code or download alpha version from https://ci.appveyor.com/nuget/optimus-private

**Comment by RusKnyaz** [comment]
Today I published version 2.3.0, try it.
