### ISSUE TITLE
Добавить методы для отправки запросов

### ISSUE THREAD

**Issue by PickGG** [RusKnyaz/Optimus#30]
1. Добавить методы для отправки запросов
2. И насчет событий в классе Engine
public event Action<Request> OnRequest;
public event Action<ReceivedEventArguments> OnResponse;
Они работают только тогда когда выполняется метод OpenUrl или они еще могут перехватывать запросы который отправляет JavaScript? Было бы очень удобно для моего проекта если бы они могли перехватывать JS.

**Comment by PickGG** [comment]
Engine.ResourceProvider.SendRequest

**Comment by RusKnyaz** [comment]
yes

**Comment by RusKnyaz** [comment]
See [manual](https://github.com/RusKnyaz/Optimus/blob/develop/docs/snippets.md#handle-request-and-response) for requests handling.
