### ISSUE TITLE
Support for plain text documents

### ISSUE THREAD

**Issue by mk1024** [RusKnyaz/Optimus#50]
**Issue**
It looks like Optimus does not support the download of plain text at the moment. How difficult would it be to add support for other document types?

**Background**
Why a simple request does not work: Even if a text file may look like a dumb static resource it may be required to fake a real browser with valid cookies to download it correctly.

**First thoughts** (before I try to create a pull request)

- A text file or any other plain text content could be represented by a `Document` that only has text as its root element or as inner html. This document could have `ResourceTypes.Text` which is already defined.
- `Engine.LoadFromResource` should not throw an exception on non-html documents and build the document according to the resource type. A `BuildDocument` for plain text only needs to read the stream and create a single root element or set the inner html.
- `Head` and `Body` of such a `Document` could just be `null`, but this would require a null check (or `Body?.`) in a few places.

What do you think?

**Comment by RusKnyaz** [comment]
Thanks for your feedback. I think there is no point in treating the text as an html document. Instead, it would be good to have a convenient way to load an arbitrary file using the current cookies.

**Comment by mk1024** [comment]
I came up with this idea, because the browser I'm currently using implements it this way ([ScrapySharp](https://github.com/rflechner/ScrapySharp#scrapysharp-can-also-simulate-a-web-browser)). This way cookies, headers und redirects work without any special handling. Thought this would be a cool feature for Otimus :-)

**Comment by RusKnyaz** [comment]
Added new extension method to Knyaz.Optimus.TestingTools class.

```C#
var resource = await engine.DownloadAsync("/file/on/your/site");
var resultStream = resource.Stream;
```
